### ISSUE TITLE
Update 1.8 quest book issues 

### ISSUE THREAD

**Issue by miner-bob-1960** [MyM-ModpackTeam/hypovolemia#354]
Chapter 1, Easing Life, Ultimate Tank, book will not detect
 No More Bones, The Quest is asking for bedrock, (don't know if this is intentional), also there is a invalid item as a reward.

 Chapter 7, Essential wireless, Essentia Coil, Book will not detect.

 Chapter 8, Discount, book will not detect any of the items.
 Even Better, book will not detect the sceptre.

 Chapter 9 Prove your cooking, ultimate stew is uncrafterble, no way to get wormwood this also effects Chapter 14
 Staffs of insane power, book will not detect Elementium kissed dreamwood staff

 Chapter 11 The elves, book wiil not detect the lexica botania, with 1, 2 or 3 schools of knowledge

 Chapter 15 Iron for days, there is no way to craft molten Iron.

 You are able to complete Chapters 2, 3 ,4 ,5 ,10 and 11 with no problems,

**Comment by tyler489** [comment]
Alright ... i fixed all ofthese how did they come back

**Comment by johnfg12** [comment]
because you didnt test AGAIN -_-

**Comment by Messiah7** [comment]
There defauls way to get wormwood - witchery mutating
[http://ftbwiki.org/Wormwood](url)

**Comment by Alifalafel** [comment]
Aside from the wormwood, most (if not all) of these are still an issue.

**Comment by YourMCGeek** [comment]
Chapter 1 - Problems should be fixed. 

Chapter 7 - Essentia Coil detected for myself. Can anyone else test this?

Chapter 8 - Discount - It detected for myself. Can someone else test this?
Even Better - It detected for myself. Can someone else test this?

Ill be working on the other chapters later

**Comment by YourMCGeek** [comment]
Ive done everything I could. Everything worked for me.. I couldnt unlock chapter 9 for some reason and there is no longer a chapter 15.

Done.

**Comment by cathrine940** [comment]
Hello. I am also being asked for bedrock on No More Bones and it will not recognise any of the tanks I make on Easing Life. I am using Hypovolemia from Curse, I presume that is the FTB version. Thank you Oh and I tried \HQM edit and it said I was not able to use that command
